// **NOTE**: this file is generated by `dhall-render`.
// You should NOT edit it manually, your changes will be lost.

ThisBuild / scalaVersion := "2.12.13"
ThisBuild / version := IO.read(new File("VERSION"))
